platform :ios, '8.2'
use_frameworks!

target 'Tally_Example' do
  pod 'Tally', :path => '../'

  target 'Tally_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
